### ISSUE TITLE
Error: "go server 启动失败，服务器将不可用" after npm run dev-all

### ISSUE THREAD

**Issue by TommyLemon** [vesoft-inc/nebula-studio#264]
**Describe the bug (__must be provided__)**
"go server 启动失败，服务器将不可用"

<img width="624" alt="image" src="https://user-images.githubusercontent.com/5738175/181555111-a9ca9283-2604-4cb4-88ee-2aa5f213139a.png">

<img width="696" alt="image" src="https://user-images.githubusercontent.com/5738175/181590789-5ccc9a44-cd8f-47fe-86ae-ebcfca7a019e.png">

<img width="1280" alt="image" src="https://user-images.githubusercontent.com/5738175/181590890-165ddb2d-c7d2-4927-b654-102535dd884e.png">

And even I couldn't connect my centos 7 server after the command for several times. It recovered after I rebooted it.

<img width="439" alt="image" src="https://user-images.githubusercontent.com/5738175/181563250-816bc64d-67f4-43e9-a167-0b83cbe3024d.png">

<img width="737" alt="image" src="https://user-images.githubusercontent.com/5738175/181561100-33d08914-1248-4010-9239-161cff4d8449.png">

**Your Environments (__must be provided__)**

* OS: Linux(CentOS 7.4 64位)
* Node-version: v10.9.0
* Studio-version: 3.4.0(https://github.com/vesoft-inc/nebula-studio/archive/refs/tags/v3.4.0.zip)

<img width="435" alt="image" src="https://user-images.githubusercontent.com/5738175/181562373-ddc7a4ab-05bb-4bfa-a571-d6ce74b70f80.png">

**How To Reproduce(__must be provided__)**

1. cd nebula-studio-3.4.0
2. npm install
3. npm run dev-all

**Expected behavior**

Run server successfully.

**Additional context**

```sh
> nebula-graph-studio@3.4.0 dev-all /www/wwwroot/nebula-studio-3.4.0
> node ./config/server.js

(node:3369) ExperimentalWarning: The fs.promises API is experimental
<i> [webpack-dev-server] [HPM] Proxy created: /api-nebula/**  -> http://127.0.0.1:9000
<i> [webpack-dev-server] [HPM] Proxy created: /api/**  -> http://127.0.0.1:9000
Listening at localhost: 7001
Opening your system browser...
server::go build -ldflags '' -o bin/studio studio.go

go server 启动失败，服务器将不可用，请切换到 server 目录调试异常

<e> [webpack-dev-middleware] HookWebpackError: Not supported
<e>     at makeWebpackError (/www/wwwroot/nebula-studio-3.4.0/node_modules/webpack/lib/HookWebpackError.js:48:9)
<e>     at hooks.processAssets.callAsync.err (/www/wwwroot/nebula-studio-3.4.0/node_modules/webpack/lib/Compilation.js:3060:12)
<e>     at eval (eval at create (/www/wwwroot/nebula-studio-3.4.0/node_modules/tapable/lib/HookCodeFactory.js:33:10), <anonymous>:52:1)
<e>     at err (/www/wwwroot/nebula-studio-3.4.0/node_modules/webpack/lib/Compilation.js:510:26)
<e>     at compilation.hooks.processAssets.tapAsync (/www/wwwroot/nebula-studio-3.4.0/node_modules/copy-webpack-plugin/dist/index.js:710:13)
<e>     at process._tickCallback (internal/process/next_tick.js:68:7)
<e> -- inner error --
<e> Error: Not supported
<e>     at compilation.hooks.processAssets.tapAsync (/www/wwwroot/nebula-studio-3.4.0/node_modules/copy-webpack-plugin/dist/index.js:706:13)
<e>     at fn (/www/wwwroot/nebula-studio-3.4.0/node_modules/webpack/lib/Compilation.js:509:9)
<e>     at Hook.eval [as callAsync] (eval at create (/www/wwwroot/nebula-studio-3.4.0/node_modules/tapable/lib/HookCodeFactory.js:33:10), <anonymous>:50:1)
<e>     at Hook.CALL_ASYNC_DELEGATE [as _callAsync] (/www/wwwroot/nebula-studio-3.4.0/node_modules/tapable/lib/Hook.js:18:14)
<e>     at cont (/www/wwwroot/nebula-studio-3.4.0/node_modules/webpack/lib/Compilation.js:3057:34)
<e>     at createChunkAssets.err (/www/wwwroot/nebula-studio-3.4.0/node_modules/webpack/lib/Compilation.js:3105:10)
<e>     at symbolIterator (/www/wwwroot/nebula-studio-3.4.0/node_modules/neo-async/async.js:3485:9)
<e>     at timesSync (/www/wwwroot/nebula-studio-3.4.0/node_modules/neo-async/async.js:2297:7)
<e>     at Object.eachLimit (/www/wwwroot/nebula-studio-3.4.0/node_modules/neo-async/async.js:3463:5)
<e>     at Compilation.createChunkAssets (/www/wwwroot/nebula-studio-3.4.0/node_modules/webpack/lib/Compilation.js:4522:12)
<e> caused by plugins in Compilation.hooks.processAssets
<e> Error: Not supported
<e>     at compilation.hooks.processAssets.tapAsync (/www/wwwroot/nebula-studio-3.4.0/node_modules/copy-webpack-plugin/dist/index.js:706:13)
<e>     at fn (/www/wwwroot/nebula-studio-3.4.0/node_modules/webpack/lib/Compilation.js:509:9)
<e>     at Hook.eval [as callAsync] (eval at create (/www/wwwroot/nebula-studio-3.4.0/node_modules/tapable/lib/HookCodeFactory.js:33:10), <anonymous>:50:1)
<e>     at Hook.CALL_ASYNC_DELEGATE [as _callAsync] (/www/wwwroot/nebula-studio-3.4.0/node_modules/tapable/lib/Hook.js:18:14)
<e>     at cont (/www/wwwroot/nebula-studio-3.4.0/node_modules/webpack/lib/Compilation.js:3057:34)
<e>     at createChunkAssets.err (/www/wwwroot/nebula-studio-3.4.0/node_modules/webpack/lib/Compilation.js:3105:10)
<e>     at symbolIterator (/www/wwwroot/nebula-studio-3.4.0/node_modules/neo-async/async.js:3485:9)
<e>     at timesSync (/www/wwwroot/nebula-studio-3.4.0/node_modules/neo-async/async.js:2297:7)
<e>     at Object.eachLimit (/www/wwwroot/nebula-studio-3.4.0/node_modules/neo-async/async.js:3463:5)
<e>     at Compilation.createChunkAssets (/www/wwwroot/nebula-studio-3.4.0/node_modules/webpack/lib/Compilation.js:4522:12)
```

**Comment by hetao92** [comment]
could you use `go run server/api/studio/studio.go` to  specific server error information. it need golang environment. 
Btw, i suggestion use rpm on CentOs directly. refer to [doc](https://docs.nebula-graph.io/3.2.0/nebula-studio/deploy-connect/st-ug-deploy/)

**Comment by TommyLemon** [comment]
> go run server/api/studio/studio.go

thx, I'll try

**Comment by TommyLemon** [comment]
@hetao92  it still shows me the same error
<img width="1108" alt="image" src="https://user-images.githubusercontent.com/5738175/182345311-d0bc67bb-c9ec-4b49-9796-211d6bc57169.png">


go run server/api/studio/studio.go
<img width="1280" alt="image" src="https://user-images.githubusercontent.com/5738175/182345905-21a70f6d-bc75-4be6-af26-8122d08c5fde.png">
```
[root@izbp110l2aupfn0cocrcmgz nebula-studio-3.4.0]# go run server/api/studio/studio.go
server/api/studio/studio.go:9:2: no required module provides package github.com/vesoft-inc/go-pkg/middleware: go.mod file not found in current directory or any parent directory; see 'go help modules'
server/api/studio/studio.go:10:2: no required module provides package github.com/vesoft-inc/nebula-http-gateway/ccore/nebula/gateway/pool: go.mod file not found in current directory or any parent directory; see 'go help modules'
server/api/studio/studio.go:11:2: no required module provides package github.com/vesoft-inc/nebula-studio/server-v2/api/studio/internal/config: go.mod file not found in current directory or any parent directory; see 'go help modules'
server/api/studio/studio.go:12:2: no required module provides package github.com/vesoft-inc/nebula-studio/server-v2/api/studio/internal/handler: go.mod file not found in current directory or any parent directory; see 'go help modules'
server/api/studio/studio.go:13:2: no required module provides package github.com/vesoft-inc/nebula-studio/server-v2/api/studio/internal/service/importer: go.mod file not found in current directory or any parent directory; see 'go help modules'
server/api/studio/studio.go:14:2: no required module provides package github.com/vesoft-inc/nebula-studio/server-v2/api/studio/internal/svc: go.mod file not found in current directory or any parent directory; see 'go help modules'
server/api/studio/studio.go:15:2: no required module provides package github.com/vesoft-inc/nebula-studio/server-v2/api/studio/pkg/auth: go.mod file not found in current directory or any parent directory; see 'go help modules'
server/api/studio/studio.go:16:2: no required module provides package github.com/vesoft-inc/nebula-studio/server-v2/api/studio/pkg/logging: go.mod file not found in current directory or any parent directory; see 'go help modules'
server/api/studio/studio.go:17:2: no required module provides package github.com/vesoft-inc/nebula-studio/server-v2/api/studio/pkg/utils: go.mod file not found in current directory or any parent directory; see 'go help modules'
server/api/studio/studio.go:18:2: no required module provides package github.com/zeromicro/go-zero/core/conf: go.mod file not found in current directory or any parent directory; see 'go help modules'
server/api/studio/studio.go:19:2: no required module provides package github.com/zeromicro/go-zero/core/proc: go.mod file not found in current directory or any parent directory; see 'go help modules'
server/api/studio/studio.go:20:2: no required module provides package github.com/zeromicro/go-zero/rest: go.mod file not found in current directory or any parent directory; see 'go help modules'
server/api/studio/studio.go:21:2: no required module provides package github.com/zeromicro/go-zero/rest/httpx: go.mod file not found in current directory or any parent directory; see 'go help modules'
server/api/studio/studio.go:22:2: no required module provides package go.uber.org/zap: go.mod file not found in current directory or any parent directory; see 'go help modules'
[root@izbp110l2aupfn0cocrcmgz nebula-studio-3.4.0]# 
[root@izbp110l2aupfn0cocrcmgz nebula-studio-3.4.0]# npm run dev-all

> nebula-graph-studio@3.4.0 dev-all /www/wwwroot/nebula-studio-3.4.0
> node ./config/server.js

(node:21246) ExperimentalWarning: The fs.promises API is experimental
<i> [webpack-dev-server] [HPM] Proxy created: /api-nebula/**  -> http://127.0.0.1:9000
<i> [webpack-dev-server] [HPM] Proxy created: /api/**  -> http://127.0.0.1:9000
process exits with code: 1
/www/wwwroot/nebula-studio-3.4.0/node_modules/webpack-dev-server/lib/Server.js:2432
        throw error;
        ^

Error: listen EADDRINUSE 127.0.0.1:7001
    at Server.setupListenHandle [as _listen2] (net.js:1334:14)
    at listenInCluster (net.js:1382:12)
    at GetAddrInfoReqWrap.doListen [as callback] (net.js:1508:7)
    at GetAddrInfoReqWrap.onlookup [as oncomplete] (dns.js:62:10)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! nebula-graph-studio@3.4.0 dev-all: `node ./config/server.js`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the nebula-graph-studio@3.4.0 dev-all script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /root/.npm/_logs/2022-08-02T09_48_11_499Z-debug.log
[root@izbp110l2aupfn0cocrcmgz nebula-studio-3.4.0]# 

```

**Comment by wey-gu** [comment]
~~Have you run backend build with:~~
```bash
cd server/api/studio
go build -o server
```
~~before "dev-all" ?~~

~~I guess go based backend should be built before starting everything up :-D.~~

update: dev-all will build the go server, too, you are doing right :-p
But still, it's worth trying for a go server build:
```
$ cd ./server/api/studio
$ make run
```

```
[root@izbp110l2aupfn0cocrcmgz nebula-studio-3.4.0]# go run server/api/studio/studio.go
...
server/api/studio/studio.go:22:2: no required module provides package go.uber.org/zap: go.mod file not found in current directory or any parent directory; see 'go help modules'
```

**Comment by veezhang** [comment]
@TommyLemon Have you tried the following commands?
```shell
cd server/api/studio
make run
```
And please paste the output if failed, thx.

**Comment by hetao92** [comment]
You don't need to execute `npm run dev-all` now. This is used to quickly start the front and back services at the same time, but it seems that your server can't start. There is a problem with golang on your virtual machine and the server fails to start. Could you use our rpm package to deploy studio directly? If you want to deploy source code, you may need to modify the configuration of golang like `go env -w GO111MODULE=auto`

**Comment by TommyLemon** [comment]
Thank you all.
I changed my server to a Ubuntu 20.04, while it still showed me the same error above.
Then I switched to a former version [3.2.3](https://github.com/vesoft-inc/nebula-studio/archive/refs/tags/v3.2.3.zip), it stepped forward a lot together with [nebula-graph 3.0.0](wget https://oss-cdn.nebula-graph.com.cn/package/3.0.0/nebula-graph-3.0.0.ubuntu2204.amd64.deb).
But there is another error:
```sh
Error from chokidar (/home/tommy/nebula-studio-3.2.3/node_modules/lodash-es): Error: ENOSPC: System limit for number of file watchers reached, watch '/home/tommy/nebula-studio-3.2.3/node_modules/lodash-es/util.default.js'
```
![image](https://user-images.githubusercontent.com/5738175/185053977-5f913ad3-ae6d-48fe-8042-b6ae3f8e1de4.png)

**Comment by TommyLemon** [comment]
> ~Have you run backend build with:~
> 
> ```shell
> cd server/api/studio
> go build -o server
> ```
> 
> ~before "dev-all" ?~
> 
> ~I guess go based backend should be built before starting everything up :-D.~
> 
> update: dev-all will build the go server, too, you are doing right :-p But still, it's worth trying for a go server build:
> 
> ```
> $ cd ./server/api/studio
> $ make run
> ```
> 
> ```
> [root@izbp110l2aupfn0cocrcmgz nebula-studio-3.4.0]# go run server/api/studio/studio.go
> ...
> server/api/studio/studio.go:22:2: no required module provides package go.uber.org/zap: go.mod file not found in current directory or any parent directory; see 'go help modules'
> ```

@wey-gu  @veezhang   No such file or directory in nebula-studio-3.2.3
```sh
^Croot@tommy:/home/tommy/nebula-studio-3.2.3# cd ./server/api/studio
bash: cd: ./server/api/studio: No such file or directory
root@tommy:/home/tommy/nebula-studio-3.2.3# cd server/api/studio
bash: cd: server/api/studio: No such file or directory
root@tommy:/home/tommy/nebula-studio-3.2.3# 
```
![image](https://user-images.githubusercontent.com/5738175/185054969-8db9b448-3b84-4101-b3cd-861fec10d34c.png)

**Comment by wey-gu** [comment]
in 3.2.3, the go server side isn't embedded in NebulaStudio, instead, it relied on the http gateway, thus there is no such folder yet.

**Comment by hetao92** [comment]
Due to no progress for a month, this issue is closed first, if you have a new update, you can open the issue again.
