### ISSUE TITLE
SyntaxError: "Unexpected token ="  after npm run dev

### ISSUE THREAD

**Issue by TommyLemon** [vesoft-inc/nebula-studio#265]
**Describe the bug (__must be provided__)**

<img width="1180" alt="image" src="https://user-images.githubusercontent.com/5738175/181589552-c020e9de-9dc9-4e48-92ad-eb4f3523f13e.png">

**Your Environments (__must be provided__)**

* OS: Linux(CentOS 7.4 64位)
* Node-version: v10.9.0
* Studio-version: 3.4.0(https://github.com/vesoft-inc/nebula-studio/archive/refs/tags/v3.4.0.zip)

<img width="435" alt="image" src="https://user-images.githubusercontent.com/5738175/181562373-ddc7a4ab-05bb-4bfa-a571-d6ce74b70f80.png">

**How To Reproduce(__must be provided__)**

1. cd nebula-studio-3.4.0
2. npm install
3. npm run dev

**Expected behavior**

Run server successfully.

**Additional context**

```sh
> nebula-graph-studio@3.4.0 dev /www/wwwroot/nebula-studio-3.4.0
> webpack-dev-server --config ./config/webpack.dev.js --mode development --color --progress --hot

<i> [webpack-dev-server] [HPM] Proxy created: /api-nebula/**  -> http://127.0.0.1:9000
<i> [webpack-dev-server] [HPM] Proxy created: /api/**  -> http://127.0.0.1:9000
10% building 0/1 entries 0/0 dependencies 0/0 modules[webpack-cli] /www/wwwroot/nebula-studio-3.4.0/node_modules/webpack-dev-server/lib/servers/WebsocketServer.js:10
  static heartbeatInterval = 1000;
                           ^

SyntaxError: Unexpected token =
    at new Script (vm.js:73:7)
    at createScript (vm.js:245:10)
    at Object.runInThisContext (vm.js:297:10)
    at Module._compile (internal/modules/cjs/loader.js:657:28)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:700:10)
    at Module.load (internal/modules/cjs/loader.js:599:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:538:12)
    at Function.Module._load (internal/modules/cjs/loader.js:530:3)
    at Module.require (internal/modules/cjs/loader.js:637:17)
    at require (internal/modules/cjs/helpers.js:20:18)
npm ERR! code ELIFECYCLE
npm ERR! errno 2
npm ERR! nebula-graph-studio@3.4.0 dev: `webpack-dev-server --config ./config/webpack.dev.js --mode development --color --progress --hot`
npm ERR! Exit status 2
npm ERR! 
npm ERR! Failed at the nebula-graph-studio@3.4.0 dev script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /root/.npm/_logs/2022-07-28T16_26_09_570Z-debug.log
```

```sh
vi /root/.npm/_logs/2022-07-28T16_26_09_570Z-debug.log
0 info it worked if it ends with ok
1 verbose cli [ '/usr/local/node-v10.9.0-linux-x64/bin/node',
1 verbose cli   '/usr/local/bin/npm',
1 verbose cli   'run',
1 verbose cli   'dev' ]
2 info using npm@6.2.0
3 info using node@v10.9.0
4 verbose run-script [ 'predev', 'dev', 'postdev' ]
5 info lifecycle nebula-graph-studio@3.4.0~predev: nebula-graph-studio@3.4.0
6 info lifecycle nebula-graph-studio@3.4.0~dev: nebula-graph-studio@3.4.0
7 verbose lifecycle nebula-graph-studio@3.4.0~dev: unsafe-perm in lifecycle true
8 verbose lifecycle nebula-graph-studio@3.4.0~dev: PATH: /usr/local/node-v10.9.0-linux-x64/lib/node_modules/npm/node_modules/npm-lifecycle/node-gyp-bin:/www/wwwroot/nebula-studio-3.4.0/node_modules/.bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/usr/lib/jvm/java-1.8.0-openjdk-1.8.0.161-0.b14.el7_4.x86_64/bin:/usr/lib/jvm/java-1.8.0-openjdk-1.8.0.161-0.b14.el7_4.x86_64/jre/bin:/opt/mssql-tools/bin:/root/bin:/opt/mssql-tools/bin
9 verbose lifecycle nebula-graph-studio@3.4.0~dev: CWD: /www/wwwroot/nebula-studio-3.4.0
10 silly lifecycle nebula-graph-studio@3.4.0~dev: Args: [ '-c',
10 silly lifecycle   'webpack-dev-server --config ./config/webpack.dev.js --mode development --color --progress --hot' ]
11 silly lifecycle nebula-graph-studio@3.4.0~dev: Returned: code: 2  signal: null
12 info lifecycle nebula-graph-studio@3.4.0~dev: Failed to exec dev script
13 verbose stack Error: nebula-graph-studio@3.4.0 dev: `webpack-dev-server --config ./config/webpack.dev.js --mode development --color --progress --hot`
13 verbose stack Exit status 2
13 verbose stack     at EventEmitter.<anonymous> (/usr/local/node-v10.9.0-linux-x64/lib/node_modules/npm/node_modules/npm-lifecycle/index.js:304:16)
13 verbose stack     at EventEmitter.emit (events.js:182:13)
13 verbose stack     at ChildProcess.<anonymous> (/usr/local/node-v10.9.0-linux-x64/lib/node_modules/npm/node_modules/npm-lifecycle/lib/spawn.js:55:14)
13 verbose stack     at ChildProcess.emit (events.js:182:13)
13 verbose stack     at maybeClose (internal/child_process.js:961:16)
13 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:250:5)
14 verbose pkgid nebula-graph-studio@3.4.0
15 verbose cwd /www/wwwroot/nebula-studio-3.4.0
16 verbose Linux 3.10.0-957.27.2.el7.x86_64
17 verbose argv "/usr/local/node-v10.9.0-linux-x64/bin/node" "/usr/local/bin/npm" "run" "dev"
18 verbose node v10.9.0
19 verbose npm  v6.2.0
20 error code ELIFECYCLE
21 error errno 2
22 error nebula-graph-studio@3.4.0 dev: `webpack-dev-server --config ./config/webpack.dev.js --mode development --color --progress --hot`
22 error Exit status 2
23 error Failed at the nebula-graph-studio@3.4.0 dev script.
23 error This is probably not a problem with npm. There is likely additional logging output above.
24 verbose exit [ 2, true ]
```

**Comment by hetao92** [comment]
please update nodejs to >14

**Comment by hetao92** [comment]
We have noticed that the issue you created hasn’t been updated for nearly a month, so we have to close it for now. If you have any new updates, you are welcome to reopen this issue anytime. Thanks a lot for your contribution.
